### ISSUE TITLE
когда обнова сука?

### ISSUE THREAD

**Issue by sidanya** [Mr666dd/Russian-Pterodactyl-1.7.0#1]
мы с семьей уже полторы секунды ждем когда вы обновите до 1.7.0

**Comment by Mr666dd** [comment]
Уважаемый IDanya. На данный момент я работаю над переводом. В скором
времени он будет готов.

сб, 5 февр. 2022 г.

**Comment by sidanya** [comment]
всё поняЛ, спасбио
