### ISSUE TITLE
Обновление или архивирование репозитория

### ISSUE THREAD

**Issue by esheodinvopros** [Mr666dd/Russian-Pterodactyl-1.7.0#5]
может или обновить перевод для новых версий, или архивировать репозиторий. или даже не архивировать а указать что проект больше не будет обновлен

**Comment by Mr666dd** [comment]
Извините что слишком долго отвечаю. 

Архивирование репозитория не будет произведено. В скором времени будет обновление.
Я понимаю, версия старая. Но у меня есть пока что нет времени. Ожидайте обновление до 1.10.1

Я добавил сюда AgeraFly, можете подождать его ответа, он может поможет.

С Уважением, Mr666dd.

**Comment by Mr666dd** [comment]
Так же прошу заметить, что вы можете сами помочь этому проекту.
Всё что нужно - отправить Pull requests с вашим кодом - переводом.

Хорошего дня, IDanya.
С Уважением, Mr666dd.

**Comment by AgeraFly** [comment]
Приветствую. 

Мы не собираемся архивировать это сия-чудо, в данный момент мы заняты развитием другого проекта. Но и про этот мы не забыли, попросту напросто у нас не хватает времени на качественный перевод с нуля, и создания дополнения.

> С уважением AgeraFly.

**Comment by esheodinvopros** [comment]
Хорошо, спасибо за ответ.
